version: '3.8'

services:
  web:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_HOST=0.0.0.0
    depends_on:
      - db

  db:
    image: sqlite:latest
    volumes:
      - db_data:/var/lib/sqlite

volumes:
  db_data: